# -*- coding: utf-8 -*-
"""leapyear2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mTQaAnzArPjaazWL9ihseE-nFJrJA2yq
"""

a = int (input("enter a year: "))
if (a%4==0 and a%100!=0):
    print(a,  "is a leap year")
elif (a%400==0):
    print(a, "is a leap year")
else:
  print(a, "is not a leap year")